import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar, Footer, Providers } from "@/components";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased light`}>
        < Providers >
          <NavBar />
          <div className="bg-custom-gradient">
            {children}
          </div>
          <Footer />
        </ Providers >
      </body>
    </html>
  );
}
